sign-commit = true
sign-tag = true

pre-release-commit-message = "Bump up version to {{version}}"
tag-message = "Version {{version}}"
dev-version = false

[[pre-release-replacements]]
file = "CHANGELOG.md"
search = '##\s*\[Unreleased\]\s*-\s*ReleaseDate'
replace = '''
## [Unreleased] - ReleaseDate

## [{{version}}] - {{date}}'''

[[pre-release-replacements]]
file = "CHANGELOG.md"
search = '\[Unreleased\]:.+HEAD'
replace = '''
[Unreleased]: https://github.com/dnaka91/tokio-shutdown/compare/v{{version}}...HEAD
[{{version}}]: https://github.com/dnaka91/tokio-shutdown/compare/v{{prev_version}}...v{{version}}'''
